version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: spring-training-db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
